version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: diorama_db
    environment:
      POSTGRES_USER: diorama_admin
      POSTGRES_PASSWORD: diorama_password
      POSTGRES_DB: diorama_db
    ports:
      - "5432:5432"
    volumes:
      - diorama_pg_data:/var/lib/postgresql/data

volumes:
  diorama_pg_data: